var searchData=
[
  ['imbitarray_0',['ImBitArray',['../struct_im_bit_array.html',1,'']]],
  ['imbitvector_1',['ImBitVector',['../struct_im_bit_vector.html',1,'']]],
  ['imchunkstream_2',['ImChunkStream',['../struct_im_chunk_stream.html',1,'']]],
  ['imchunkstream_3c_20imguitablesettings_20_3e_3',['ImChunkStream&lt; ImGuiTableSettings &gt;',['../struct_im_chunk_stream.html',1,'']]],
  ['imchunkstream_3c_20imguiwindowsettings_20_3e_4',['ImChunkStream&lt; ImGuiWindowSettings &gt;',['../struct_im_chunk_stream.html',1,'']]],
  ['imcolor_5',['ImColor',['../struct_im_color.html',1,'']]],
  ['imdrawchannel_6',['ImDrawChannel',['../struct_im_draw_channel.html',1,'']]],
  ['imdrawcmd_7',['ImDrawCmd',['../struct_im_draw_cmd.html',1,'']]],
  ['imdrawcmdheader_8',['ImDrawCmdHeader',['../struct_im_draw_cmd_header.html',1,'']]],
  ['imdrawdata_9',['ImDrawData',['../struct_im_draw_data.html',1,'']]],
  ['imdrawdatabuilder_10',['ImDrawDataBuilder',['../struct_im_draw_data_builder.html',1,'']]],
  ['imdrawlist_11',['ImDrawList',['../struct_im_draw_list.html',1,'']]],
  ['imdrawlistshareddata_12',['ImDrawListSharedData',['../struct_im_draw_list_shared_data.html',1,'']]],
  ['imdrawlistsplitter_13',['ImDrawListSplitter',['../struct_im_draw_list_splitter.html',1,'']]],
  ['imdrawvert_14',['ImDrawVert',['../struct_im_draw_vert.html',1,'']]],
  ['imfont_15',['ImFont',['../struct_im_font.html',1,'']]],
  ['imfontatlas_16',['ImFontAtlas',['../struct_im_font_atlas.html',1,'']]],
  ['imfontatlascustomrect_17',['ImFontAtlasCustomRect',['../struct_im_font_atlas_custom_rect.html',1,'']]],
  ['imfontbuilddstdata_18',['ImFontBuildDstData',['../struct_im_font_build_dst_data.html',1,'']]],
  ['imfontbuilderio_19',['ImFontBuilderIO',['../struct_im_font_builder_i_o.html',1,'']]],
  ['imfontbuildsrcdata_20',['ImFontBuildSrcData',['../struct_im_font_build_src_data.html',1,'']]],
  ['imfontconfig_21',['ImFontConfig',['../struct_im_font_config.html',1,'']]],
  ['imfontglyph_22',['ImFontGlyph',['../struct_im_font_glyph.html',1,'']]],
  ['imfontglyphrangesbuilder_23',['ImFontGlyphRangesBuilder',['../struct_im_font_glyph_ranges_builder.html',1,'']]],
  ['imgui_5fimpldx11_5fdata_24',['ImGui_ImplDX11_Data',['../struct_im_gui___impl_d_x11___data.html',1,'']]],
  ['imgui_5fimpldx11_5fviewportdata_25',['ImGui_ImplDX11_ViewportData',['../struct_im_gui___impl_d_x11___viewport_data.html',1,'']]],
  ['imgui_5fimplwin32_5fdata_26',['ImGui_ImplWin32_Data',['../struct_im_gui___impl_win32___data.html',1,'']]],
  ['imgui_5fimplwin32_5fviewportdata_27',['ImGui_ImplWin32_ViewportData',['../struct_im_gui___impl_win32___viewport_data.html',1,'']]],
  ['imguicolormod_28',['ImGuiColorMod',['../struct_im_gui_color_mod.html',1,'']]],
  ['imguicombopreviewdata_29',['ImGuiComboPreviewData',['../struct_im_gui_combo_preview_data.html',1,'']]],
  ['imguicontext_30',['ImGuiContext',['../struct_im_gui_context.html',1,'']]],
  ['imguicontexthook_31',['ImGuiContextHook',['../struct_im_gui_context_hook.html',1,'']]],
  ['imguidatatypeinfo_32',['ImGuiDataTypeInfo',['../struct_im_gui_data_type_info.html',1,'']]],
  ['imguidatatypetempstorage_33',['ImGuiDataTypeTempStorage',['../struct_im_gui_data_type_temp_storage.html',1,'']]],
  ['imguidatavarinfo_34',['ImGuiDataVarInfo',['../struct_im_gui_data_var_info.html',1,'']]],
  ['imguidockcontext_35',['ImGuiDockContext',['../struct_im_gui_dock_context.html',1,'']]],
  ['imguidockcontextprunenodedata_36',['ImGuiDockContextPruneNodeData',['../struct_im_gui_dock_context_prune_node_data.html',1,'']]],
  ['imguidocknode_37',['ImGuiDockNode',['../struct_im_gui_dock_node.html',1,'']]],
  ['imguidocknodesettings_38',['ImGuiDockNodeSettings',['../struct_im_gui_dock_node_settings.html',1,'']]],
  ['imguidocknodetreeinfo_39',['ImGuiDockNodeTreeInfo',['../struct_im_gui_dock_node_tree_info.html',1,'']]],
  ['imguidockpreviewdata_40',['ImGuiDockPreviewData',['../struct_im_gui_dock_preview_data.html',1,'']]],
  ['imguidockrequest_41',['ImGuiDockRequest',['../struct_im_gui_dock_request.html',1,'']]],
  ['imguigroupdata_42',['ImGuiGroupData',['../struct_im_gui_group_data.html',1,'']]],
  ['imguiinputevent_43',['ImGuiInputEvent',['../struct_im_gui_input_event.html',1,'']]],
  ['imguiinputeventappfocused_44',['ImGuiInputEventAppFocused',['../struct_im_gui_input_event_app_focused.html',1,'']]],
  ['imguiinputeventkey_45',['ImGuiInputEventKey',['../struct_im_gui_input_event_key.html',1,'']]],
  ['imguiinputeventmousebutton_46',['ImGuiInputEventMouseButton',['../struct_im_gui_input_event_mouse_button.html',1,'']]],
  ['imguiinputeventmousepos_47',['ImGuiInputEventMousePos',['../struct_im_gui_input_event_mouse_pos.html',1,'']]],
  ['imguiinputeventmouseviewport_48',['ImGuiInputEventMouseViewport',['../struct_im_gui_input_event_mouse_viewport.html',1,'']]],
  ['imguiinputeventmousewheel_49',['ImGuiInputEventMouseWheel',['../struct_im_gui_input_event_mouse_wheel.html',1,'']]],
  ['imguiinputeventtext_50',['ImGuiInputEventText',['../struct_im_gui_input_event_text.html',1,'']]],
  ['imguiinputtextcallbackdata_51',['ImGuiInputTextCallbackData',['../struct_im_gui_input_text_callback_data.html',1,'']]],
  ['imguiinputtextstate_52',['ImGuiInputTextState',['../struct_im_gui_input_text_state.html',1,'']]],
  ['imguiio_53',['ImGuiIO',['../struct_im_gui_i_o.html',1,'']]],
  ['imguikeydata_54',['ImGuiKeyData',['../struct_im_gui_key_data.html',1,'']]],
  ['imguikeyownerdata_55',['ImGuiKeyOwnerData',['../struct_im_gui_key_owner_data.html',1,'']]],
  ['imguikeyroutingdata_56',['ImGuiKeyRoutingData',['../struct_im_gui_key_routing_data.html',1,'']]],
  ['imguikeyroutingtable_57',['ImGuiKeyRoutingTable',['../struct_im_gui_key_routing_table.html',1,'']]],
  ['imguilastitemdata_58',['ImGuiLastItemData',['../struct_im_gui_last_item_data.html',1,'']]],
  ['imguilistclipper_59',['ImGuiListClipper',['../struct_im_gui_list_clipper.html',1,'']]],
  ['imguilistclipperdata_60',['ImGuiListClipperData',['../struct_im_gui_list_clipper_data.html',1,'']]],
  ['imguilistclipperrange_61',['ImGuiListClipperRange',['../struct_im_gui_list_clipper_range.html',1,'']]],
  ['imguilocentry_62',['ImGuiLocEntry',['../struct_im_gui_loc_entry.html',1,'']]],
  ['imguimenucolumns_63',['ImGuiMenuColumns',['../struct_im_gui_menu_columns.html',1,'']]],
  ['imguimetricsconfig_64',['ImGuiMetricsConfig',['../struct_im_gui_metrics_config.html',1,'']]],
  ['imguinavitemdata_65',['ImGuiNavItemData',['../struct_im_gui_nav_item_data.html',1,'']]],
  ['imguinextitemdata_66',['ImGuiNextItemData',['../struct_im_gui_next_item_data.html',1,'']]],
  ['imguinextwindowdata_67',['ImGuiNextWindowData',['../struct_im_gui_next_window_data.html',1,'']]],
  ['imguioldcolumndata_68',['ImGuiOldColumnData',['../struct_im_gui_old_column_data.html',1,'']]],
  ['imguioldcolumns_69',['ImGuiOldColumns',['../struct_im_gui_old_columns.html',1,'']]],
  ['imguionceuponaframe_70',['ImGuiOnceUponAFrame',['../struct_im_gui_once_upon_a_frame.html',1,'']]],
  ['imguipayload_71',['ImGuiPayload',['../struct_im_gui_payload.html',1,'']]],
  ['imguiplatformimedata_72',['ImGuiPlatformImeData',['../struct_im_gui_platform_ime_data.html',1,'']]],
  ['imguiplatformio_73',['ImGuiPlatformIO',['../struct_im_gui_platform_i_o.html',1,'']]],
  ['imguiplatformmonitor_74',['ImGuiPlatformMonitor',['../struct_im_gui_platform_monitor.html',1,'']]],
  ['imguiplotarraygetterdata_75',['ImGuiPlotArrayGetterData',['../struct_im_gui_plot_array_getter_data.html',1,'']]],
  ['imguipopupdata_76',['ImGuiPopupData',['../struct_im_gui_popup_data.html',1,'']]],
  ['imguiptrorindex_77',['ImGuiPtrOrIndex',['../struct_im_gui_ptr_or_index.html',1,'']]],
  ['imguiresizeborderdef_78',['ImGuiResizeBorderDef',['../struct_im_gui_resize_border_def.html',1,'']]],
  ['imguiresizegripdef_79',['ImGuiResizeGripDef',['../struct_im_gui_resize_grip_def.html',1,'']]],
  ['imguisettingshandler_80',['ImGuiSettingsHandler',['../struct_im_gui_settings_handler.html',1,'']]],
  ['imguishrinkwidthitem_81',['ImGuiShrinkWidthItem',['../struct_im_gui_shrink_width_item.html',1,'']]],
  ['imguisizecallbackdata_82',['ImGuiSizeCallbackData',['../struct_im_gui_size_callback_data.html',1,'']]],
  ['imguistacklevelinfo_83',['ImGuiStackLevelInfo',['../struct_im_gui_stack_level_info.html',1,'']]],
  ['imguistacksizes_84',['ImGuiStackSizes',['../struct_im_gui_stack_sizes.html',1,'']]],
  ['imguistacktool_85',['ImGuiStackTool',['../struct_im_gui_stack_tool.html',1,'']]],
  ['imguistorage_86',['ImGuiStorage',['../struct_im_gui_storage.html',1,'']]],
  ['imguistoragepair_87',['ImGuiStoragePair',['../struct_im_gui_storage_1_1_im_gui_storage_pair.html',1,'ImGuiStorage']]],
  ['imguistyle_88',['ImGuiStyle',['../struct_im_gui_style.html',1,'']]],
  ['imguistylemod_89',['ImGuiStyleMod',['../struct_im_gui_style_mod.html',1,'']]],
  ['imguitabbar_90',['ImGuiTabBar',['../struct_im_gui_tab_bar.html',1,'']]],
  ['imguitabbarsection_91',['ImGuiTabBarSection',['../struct_im_gui_tab_bar_section.html',1,'']]],
  ['imguitabitem_92',['ImGuiTabItem',['../struct_im_gui_tab_item.html',1,'']]],
  ['imguitable_93',['ImGuiTable',['../struct_im_gui_table.html',1,'']]],
  ['imguitablecelldata_94',['ImGuiTableCellData',['../struct_im_gui_table_cell_data.html',1,'']]],
  ['imguitablecolumn_95',['ImGuiTableColumn',['../struct_im_gui_table_column.html',1,'']]],
  ['imguitablecolumnsettings_96',['ImGuiTableColumnSettings',['../struct_im_gui_table_column_settings.html',1,'']]],
  ['imguitablecolumnsortspecs_97',['ImGuiTableColumnSortSpecs',['../struct_im_gui_table_column_sort_specs.html',1,'']]],
  ['imguitableinstancedata_98',['ImGuiTableInstanceData',['../struct_im_gui_table_instance_data.html',1,'']]],
  ['imguitablesettings_99',['ImGuiTableSettings',['../struct_im_gui_table_settings.html',1,'']]],
  ['imguitablesortspecs_100',['ImGuiTableSortSpecs',['../struct_im_gui_table_sort_specs.html',1,'']]],
  ['imguitabletempdata_101',['ImGuiTableTempData',['../struct_im_gui_table_temp_data.html',1,'']]],
  ['imguitextbuffer_102',['ImGuiTextBuffer',['../struct_im_gui_text_buffer.html',1,'']]],
  ['imguitextfilter_103',['ImGuiTextFilter',['../struct_im_gui_text_filter.html',1,'']]],
  ['imguitextindex_104',['ImGuiTextIndex',['../struct_im_gui_text_index.html',1,'']]],
  ['imguitextrange_105',['ImGuiTextRange',['../struct_im_gui_text_filter_1_1_im_gui_text_range.html',1,'ImGuiTextFilter']]],
  ['imguiviewport_106',['ImGuiViewport',['../struct_im_gui_viewport.html',1,'']]],
  ['imguiviewportp_107',['ImGuiViewportP',['../struct_im_gui_viewport_p.html',1,'']]],
  ['imguiwindow_108',['ImGuiWindow',['../struct_im_gui_window.html',1,'']]],
  ['imguiwindowclass_109',['ImGuiWindowClass',['../struct_im_gui_window_class.html',1,'']]],
  ['imguiwindowdockstyle_110',['ImGuiWindowDockStyle',['../struct_im_gui_window_dock_style.html',1,'']]],
  ['imguiwindowsettings_111',['ImGuiWindowSettings',['../struct_im_gui_window_settings.html',1,'']]],
  ['imguiwindowstackdata_112',['ImGuiWindowStackData',['../struct_im_gui_window_stack_data.html',1,'']]],
  ['imguiwindowtempdata_113',['ImGuiWindowTempData',['../struct_im_gui_window_temp_data.html',1,'']]],
  ['imnewwrapper_114',['ImNewWrapper',['../struct_im_new_wrapper.html',1,'']]],
  ['impool_115',['ImPool',['../struct_im_pool.html',1,'']]],
  ['impool_3c_20imguitabbar_20_3e_116',['ImPool&lt; ImGuiTabBar &gt;',['../struct_im_pool.html',1,'']]],
  ['impool_3c_20imguitable_20_3e_117',['ImPool&lt; ImGuiTable &gt;',['../struct_im_pool.html',1,'']]],
  ['imrect_118',['ImRect',['../struct_im_rect.html',1,'']]],
  ['imspan_119',['ImSpan',['../struct_im_span.html',1,'']]],
  ['imspan_3c_20imguitablecelldata_20_3e_120',['ImSpan&lt; ImGuiTableCellData &gt;',['../struct_im_span.html',1,'']]],
  ['imspan_3c_20imguitablecolumn_20_3e_121',['ImSpan&lt; ImGuiTableColumn &gt;',['../struct_im_span.html',1,'']]],
  ['imspan_3c_20imguitablecolumnidx_20_3e_122',['ImSpan&lt; ImGuiTableColumnIdx &gt;',['../struct_im_span.html',1,'']]],
  ['imspanallocator_123',['ImSpanAllocator',['../struct_im_span_allocator.html',1,'']]],
  ['imvec1_124',['ImVec1',['../struct_im_vec1.html',1,'']]],
  ['imvec2_125',['ImVec2',['../struct_im_vec2.html',1,'']]],
  ['imvec2ih_126',['ImVec2ih',['../struct_im_vec2ih.html',1,'']]],
  ['imvec4_127',['ImVec4',['../struct_im_vec4.html',1,'']]],
  ['imvector_128',['ImVector',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20char_20_2a_20_3e_129',['ImVector&lt; char * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20char_20_3e_130',['ImVector&lt; char &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20const_20char_20_2a_20_3e_131',['ImVector&lt; const char * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20float_20_3e_132',['ImVector&lt; float &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawchannel_20_3e_133',['ImVector&lt; ImDrawChannel &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawcmd_20_3e_134',['ImVector&lt; ImDrawCmd &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawidx_20_3e_135',['ImVector&lt; ImDrawIdx &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawlist_20_2a_20_3e_136',['ImVector&lt; ImDrawList * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawvert_20_3e_137',['ImVector&lt; ImDrawVert &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfont_20_2a_20_3e_138',['ImVector&lt; ImFont * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontatlascustomrect_20_3e_139',['ImVector&lt; ImFontAtlasCustomRect &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontconfig_20_3e_140',['ImVector&lt; ImFontConfig &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontglyph_20_3e_141',['ImVector&lt; ImFontGlyph &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguicolormod_20_3e_142',['ImVector&lt; ImGuiColorMod &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguicontexthook_20_3e_143',['ImVector&lt; ImGuiContextHook &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguidocknodesettings_20_3e_144',['ImVector&lt; ImGuiDockNodeSettings &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguidockrequest_20_3e_145',['ImVector&lt; ImGuiDockRequest &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguigroupdata_20_3e_146',['ImVector&lt; ImGuiGroupData &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiid_20_3e_147',['ImVector&lt; ImGuiID &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiinputevent_20_3e_148',['ImVector&lt; ImGuiInputEvent &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiitemflags_20_3e_149',['ImVector&lt; ImGuiItemFlags &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguikeyroutingdata_20_3e_150',['ImVector&lt; ImGuiKeyRoutingData &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguilistclipperdata_20_3e_151',['ImVector&lt; ImGuiListClipperData &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguilistclipperrange_20_3e_152',['ImVector&lt; ImGuiListClipperRange &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguioldcolumndata_20_3e_153',['ImVector&lt; ImGuiOldColumnData &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguioldcolumns_20_3e_154',['ImVector&lt; ImGuiOldColumns &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiplatformmonitor_20_3e_155',['ImVector&lt; ImGuiPlatformMonitor &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguipopupdata_20_3e_156',['ImVector&lt; ImGuiPopupData &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiptrorindex_20_3e_157',['ImVector&lt; ImGuiPtrOrIndex &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguisettingshandler_20_3e_158',['ImVector&lt; ImGuiSettingsHandler &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguishrinkwidthitem_20_3e_159',['ImVector&lt; ImGuiShrinkWidthItem &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguistacklevelinfo_20_3e_160',['ImVector&lt; ImGuiStackLevelInfo &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguistorage_3a_3aimguistoragepair_20_3e_161',['ImVector&lt; ImGuiStorage::ImGuiStoragePair &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguistylemod_20_3e_162',['ImVector&lt; ImGuiStyleMod &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitabbar_20_3e_163',['ImVector&lt; ImGuiTabBar &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitabitem_20_3e_164',['ImVector&lt; ImGuiTabItem &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitable_20_3e_165',['ImVector&lt; ImGuiTable &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitablecolumnsortspecs_20_3e_166',['ImVector&lt; ImGuiTableColumnSortSpecs &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitableinstancedata_20_3e_167',['ImVector&lt; ImGuiTableInstanceData &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitabletempdata_20_3e_168',['ImVector&lt; ImGuiTableTempData &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitextfilter_3a_3aimguitextrange_20_3e_169',['ImVector&lt; ImGuiTextFilter::ImGuiTextRange &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiviewport_20_2a_20_3e_170',['ImVector&lt; ImGuiViewport * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiviewportp_20_2a_20_3e_171',['ImVector&lt; ImGuiViewportP * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiwindow_20_2a_20_3e_172',['ImVector&lt; ImGuiWindow * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiwindowstackdata_20_3e_173',['ImVector&lt; ImGuiWindowStackData &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imtextureid_20_3e_174',['ImVector&lt; ImTextureID &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imu32_20_3e_175',['ImVector&lt; ImU32 &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imvec2_20_3e_176',['ImVector&lt; ImVec2 &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imvec4_20_3e_177',['ImVector&lt; ImVec4 &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imwchar_20_3e_178',['ImVector&lt; ImWchar &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20int_20_3e_179',['ImVector&lt; int &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20mydocument_20_3e_180',['ImVector&lt; MyDocument &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20unsigned_20char_20_3e_181',['ImVector&lt; unsigned char &gt;',['../struct_im_vector.html',1,'']]],
  ['interface_182',['Interface',['../class_interface.html',1,'']]]
];
